### PR TITLE
This pull adds some null checks and bumps the cfml.parsing dependencies

### PR DESCRIPTION
**Pull request by denuno**
It also fixes a test that expected a parse error that is no longer a parse error.

### CODE REVIEW

**Comment by ryaneberly** [comment]
Looks great.   The only concern I have is adding the cfmlprojects.org repo -- even for prerelease cfparser versions.  

Thoughts?

**Comment by denuno** [comment]
I added the cfmlprojects repo to get the test to pass, as I don't know how long it takes to get the cfml.parsing artifacts into maven central, and that's also where I build CFEclipse (using Tycho), so having fresh-from-the-oven dependencies is handy.

I'm down for whatever.  We should probably take a look at the build pipeline, and maybe start a develop branch that uses -SNAPSHOT (for CFLint and cfml.parsing) vs. bumping the versions so often...  also it's a bit odd with the maven/gradle mix (I keep forgetting to test the gradle build).

I would think we could have the snapshots go up to maven central pretty fast, and not worry about adding the cfmlprojects repo, but I'm not sure how that process works... how do the artifacts get up to central?

**Comment by ryaneberly** [comment]
Regarding the gradle/maven mix, I hear you.  Jerron proposed switching to
gradle, which I supported.  However, we've been supporting both for while.

The last few releases, I've performed using maven.  Basically, uncomment
the first 3 plugins in the pom, make sure your settings.xml has your
sonatype account and password, and then run the commands listed at the end
of the cfparser pom (in comments, starting at line 176 ).   This could be
cleaned up with profiles or something of that nature.

Do you have a sonatype account?  we can get you setup for cfparser and
cflint

**Comment by denuno** [comment]
I do have a sonatype account.  It's under cfmlprojects, and theoretically you can add it as a user and then I'll be able to push builds too.  Once we've done that, and added a profile for deployment like you did for cfparser, we can ditch cfmlprojects as a repo, though it shouldn't hurt anything by having it as a fallback (pretty sure the other two will get checked first).

I got my branches kind of mixed up (didn't realize there was a dev for CFLint) and before things got any crazier I wanted to get everything in sync again, so I went ahead and synced everything up.  All the tests seem to pass, and figured it should be okay-- but if not, my bad.

When we get the sonatype stuff going, it would be good to link it up to CI (at least snapshots) so one of us doesn't have to manually get the artifacts up there.

**Comment by ryaneberly** [comment]
Just saw this thread.
 I added this jira req to sonatype to add you as a committer.

https://issues.sonatype.org/browse/NEXUS-10260

**Pull request merged**
