### PR TITLE
Refactor levels

### PR DESCRIPTION
**Pull request by justinmclean**
I've changed the level array into an enum someone mind reviewing? Thanks.

### CODE REVIEW

**Comment by justinmclean** [comment]
Ah ignore that I need to update the tests

**Comment by justinmclean** [comment]
OK all good to review now thanks!

**Comment by ryaneberly** [comment]
I like it.  Looks good.  It may break the CFLint Jenkins plugin, but we'll address it if we need to.   This is the right direction.

**Comment by justinmclean** [comment]
I can test with the CFLint Jenkins plugin before merging

**Comment by ryaneberly** [comment]
I haven't touched the plugin for a long time, actually now that I think
about it -- it just works off the output. Your change should be fine.

**Comment by TheRealAgentK** [comment]
@ryaneberly Yes, pretty sure the plugin is driven by the output xml. That being said, my changes to that might have broken the plugin anyway already. And 1.3/2.0 might break it again and more :)

**Pull request merged**
