### PR TITLE
#450

### PR DESCRIPTION
**Pull request by ryaneberly**
cfparser 2.5.5 fixes NPE in parsing

### CODE REVIEW

**Comment by ryaneberly** [comment]
when cfparser 2.5.5 is out on maven this weekend (https://mvnrepository.com/artifact/com.github.cfparser/cfparser)
This PR can be merged.

**Comment by justinmclean** [comment]
Guess there's no need for my fix for #453 then?

**Comment by ryaneberly** [comment]
453?  That's this PR.

**Comment by ryaneberly** [comment]
Oh 452.  No harm in making the plugin less fragile.   You keep it from blowing up --- but it should have been getting a valid non-null string from the parser.

**Pull request merged**
