### PR TITLE
Add -stdin and -stdout command line options

### PR DESCRIPTION
**Pull request by sjmatta**
This is a redo of pull request #83. I addressed @ryaneberly's second and third points. To the first: I'm not sure how to remove the `-stdout` param unless the defaults for filenames are removed. Maybe I'm missing something obvious. What do you think?

### CODE REVIEW

**Comment by ryaneberly** [comment]
-stdout would be required for xml or html outputs which have a default outfile.   Sounds good.  leave -stdout in, I hestitate to remove the default out file names.   Too many other plugin users may be depending on the defaults.

**Comment by sjmatta** [comment]
Ok cool. Let me know if there is anything else I can do.

**Comment by ryaneberly** [comment]
let's merge this to dev.  @jerronjames  is getting ready to release - maybe this weekend.  Don't want to mix that up.

**Comment by sjmatta** [comment]
See #113. Thanks!

**Pull request closed without merging**
