### PR TITLE
Added rule to check for repeated hard coded values

### PR DESCRIPTION
**Pull request by justinmclean**

### CODE REVIEW

**Comment by ryaneberly** [comment]
I think this has the same problem as one of the prior checkers with not resetting for each new component.

However..  Literals used across multiple components might be worth checking as well.  But that would be a different rule in my opinion - probably with stricter parameters on what a literals to check.  

I would say any 1 digit number is not worth reporting.  But would make the length of string or number of digits configurable.

Great addition.

**Comment by justinmclean** [comment]
It's not being reset on purpose so to detect the some hard coded values in different files - see comment in file. I run it over some poor quality code and it seems than 0 and 1 give too many false positives but other single digit numbers were worth checking for, of course it may depend on your code base. I see what I can do to make it a little more customisable.

**Comment by ryaneberly** [comment]
Ok, I understand.

Given that, we should report all (or the first N) of the components/files where the literal was encountered.  Just reporting the one where the threshold was hit leaves the user having to search for the others.  

Though I still think that duplication within the same file should be different (and of higher priority) than violations across multiple files.

**Comment by justinmclean** [comment]
I consider reporting all of them but it can get very verbose - is that what we want?

If we split it up to within file and across files I'd actually see the across file issues as more important i.e. they should be dinghies in either of the class or more likely in a new class.

**Comment by ryaneberly** [comment]
That makes sense.

Would you include (some) other matching files in the message portion?   I see your point about verbosity - but I don't have a problem with reporting all files with the duplicate up to a threshold.

**Comment by justinmclean** [comment]
How's these changes?

**Comment by ryaneberly** [comment]
On the pull request?   not seeing them.

**Comment by justinmclean** [comment]
Sorry, should be there now, sometimes github gets the better of me.

**Comment by ryaneberly** [comment]
:-).  Looks good.

**Pull request merged**
