### PR TITLE
Line number bug in unused variable tag functions.

### PR DESCRIPTION
**Pull request by playedinane**
Was having some trouble running the test cases. The line numbers appeared out of sync with the error indexes.

### CODE REVIEW

**Comment by justinmclean** [comment]
Odd as not seeing the issue in dev here. Travis is reporting some test failure related to lines numbers with your changes.

**Comment by ryaneberly** [comment]
@playedinane, you running on Mac or Linux, by any chance?

**Comment by playedinane** [comment]
mac

**Comment by playedinane** [comment]
i tried it a couple of time, after the change works fine

**Comment by playedinane** [comment]
Apache Maven 3.3.3

Java version: 1.8.0_65

osx 10.11.1

**Comment by playedinane** [comment]
testMultipleUnusedVarFunctionInTag(com.cflint.TestUnusedLocalVarChecker)
Time elapsed: 0.065 sec  <<< FAILURE!

java.lang.AssertionError: expected:<6> but was:<5>

at org.junit.Assert.fail(Assert.java:88)

at org.junit.Assert.failNotEquals(Assert.java:743)

at org.junit.Assert.assertEquals(Assert.java:118)

at org.junit.Assert.assertEquals(Assert.java:555)

at org.junit.Assert.assertEquals(Assert.java:542)

at
com.cflint.TestUnusedLocalVarChecker.testMultipleUnusedVarFunctionInTag(TestUnusedLocalVarChecker.java:254)

**Comment by playedinane** [comment]
We wont be be running it on os x, was just a test compile, no issue with the precompiled jar.

**Comment by justinmclean** [comment]
I allso run on OSX and it's a Java version issue on Java 1.7 the test pass on Java 1.8 they fail. With your patch on 1.7 they fail but on 1.8 they pass.

**Comment by playedinane** [comment]
Thanks for looking at it!

**Comment by justinmclean** [comment]
Given Java 1.7 is EOLed I think we should make Java 1.8 the minimum required and accept the patch. @ryaneberly what do you think?

**Comment by playedinane** [comment]
I don't have 1.7 available to experiment, but:

public List<BugInfo> getFlatBugList() {
final List<BugInfo> retval = new ArrayList<BugInfo>();
for (final List<BugInfo> list : bugList.values()) {
retval.addAll(list);
}
return retval;

}

must be looping in a different order?

maybe when we add them we can track the order?

**Comment by justinmclean** [comment]
We could do there a TODO in the code mentioning that :-)

**Comment by playedinane** [comment]
Heh, we can use a LinkedHashMap, that breaks an extra 3 (1.8) at the moment, but might be more predictable. When I get access to 1.7 I'll try across both. In the mean time I have closed the request, will submit again if I have some luck.

**Comment by ryaneberly** [comment]
Well.
There is no contract that the values() function will be consistent in it's ordering.  We should treat this as a bug.  

We could make the test tolerant of different orders, but I think I'd rather make the getFlatBugList() predictable.

**Comment by playedinane** [comment]
Yeah I agree

**Pull request closed without merging**
