### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by steinbrueckri**

### CODE REVIEW

**Comment by TheRealAgentK** [comment]
Hey @steinbrueckri - thanks for the Pull Request. Could you provide a bit of context around it? E.g. what you're trying to achieve/solve?

**Comment by steinbrueckri** [comment]
Hi @TheRealAgentK ,
I need CFLint for another project in a CI/CD Pipline for testing and therefore the Dockerfile. I have now adapted Travis to successfully create an image. I'm currently building the image in my fork and pushing it [into my namespace on Dockerhub](https://cloud.docker.com/u/z3rogate/repository/docker/z3rogate/cflint) because I needed it yesterday. It would be nicer if you could build it so that others could use CFLint in the container and it can also be found under the name cflint/CFLint on Dockerhub.

🍺  Cherrs Richard

**Comment by steinbrueckri** [comment]
bump

**Comment by ryaneberly** [comment]
Thanks @steinbrueckri - as far as I'm concerned feel free to stake out the cflint/CFLint namespace on dockerhub.  If you need any additional changes to accomplish that let us know.

**Pull request merged**
