### PR TITLE
Rule to check function return type exists or is any

### PR DESCRIPTION
**Pull request by justinmclean**

### CODE REVIEW

**Comment by ryaneberly** [comment]
@justinmclean 
Looks good.  To include the new plugins in a lint run without a custom config, I believe they will need to be added to 
src/main/resources/cflint.definition.xml

If it is in there, 

      context.addMessage("ARG_HINT_MISSING", name);

should work as well.  FYI.

**Comment by justinmclean** [comment]
Thanks for that I'll give it a go and then merge into develop. Might take a few days as I'm at a conference giving a couple lot talks.

**Comment by ryaneberly** [comment]
No problem.  Thanks for contributing.  Any of your talks on ColdFusion? :-)

**Comment by justinmclean** [comment]
Off topic but as you asked - No CF talks but 2 on Apache Flex, 1 on IoT and 1 on forensic analysis of version control history. At ApacheCon in Budapest :-)

**Comment by ryaneberly** [comment]
Enjoy.

**Pull request merged**
