### PR TITLE
Added simple hint checker

### PR DESCRIPTION
**Pull request by justinmclean**
Simple hint checker for cfcomponent, cffunction and cfargument. Just seeing how simple this is to extend.

### CODE REVIEW

**Comment by justinmclean** [comment]
I'm having a little trouble getting these rules added so that they run outside the tests. Is there any code I need to change elsewhere in the code base in order to run the rules? I also had issues getting includeRule and excludeRule to work but that's probably an issue at my end.

**Comment by ryaneberly** [comment]
Looks great.  One suggestion.

CFLint.java lines 366-372 is handling the cfcomponent tag. Lines 438-440 are handling the cfscript component declaration.   You should be able to determine the component tag at these points rather than from the file name  (which you could still execute if for some reason the initial method yields nothing)

Something like
elem.getAttributeValue("name")
and 
(CFCompDeclStatement) expression).getAttribute("name")
respectively.

The set the component name on the context.

Good work

**Comment by justinmclean** [comment]
Thanks for the suggestion. I'll give it a go at fixing it up and I should have a couple more pull requests for you in the near future.

**Comment by ryaneberly** [comment]
sounds great. thanks!.

**Comment by justinmclean** [comment]
This better?

**Comment by ryaneberly** [comment]
Looks good.  Go ahead and merge it.

Nice work!

**Pull request merged**
