### PR TITLE
Workaround context leaking

### PR DESCRIPTION
**Pull request by tstec**
In some situations CFMLParser mixes content of analyzed files. That's why we need to create separate instance of CFMLParser for each file.

### CODE REVIEW

**Comment by ryaneberly** [comment]
This one is interesting, can you possible provide a code sample of it leaking?

**Comment by tstec** [comment]
I couldn't pinpoint set of classes that are responsible for this problem. This bug appear every time I do full project analyse and it's repeatable every time.

**Comment by ryaneberly** [comment]
I added a reset() method to CFMLParser (cfparser 2.6.7), and added it to CFLint.fireStartedProcessing()

Can you try that and see if it fixes the issue.

**Comment by tstec** [comment]
Below are errors that occurred when I've executed code analysis with yours modifications.

Error 1.
Console is now full of analysed code, e.g.
```
INFO:   var redirectURL = (sslRedirection)?'https://':'http://';
INFO: redirectURL = cgi.server_name;
INFO: redirectURL = cgi.original_request_uri;
INFO:   if(len(trim(cgi.original_query_string)) )     {
INFO: redirectURL = '?';
INFO: redirectURL = cgi.original_query_string;
INFO:
INFO:     };
```
Previous version wasn't so verbose.

Error 2.
After some time StackOverflowError occurs. Before changes, full code analyse, have always finished successfully. 

```
ERROR: Exception in thread "main" java.lang.StackOverflowError
ERROR:  at cfml.parsing.cfscript.CFMember.Decompile(CFMember.java:30)
ERROR:  at cfml.parsing.cfscript.CFFullVarExpression.Decompile(CFFullVarExpression.java:64)
ERROR:  at cfml.parsing.cfscript.CFFunctionExpression.Decompile(CFFunctionExpression.java:50)
ERROR:  at cfml.parsing.cfscript.CFFullVarExpression.Decompile(CFFullVarExpression.java:64)
ERROR:  at cfml.parsing.cfscript.script.CFExpressionStatement.Decompile(CFExpressionStatement.java:17)
ERROR:  at cfml.parsing.cfscript.script.CFCompoundStatement.Decompile(CFCompoundStatement.java:54)
ERROR:  at cfml.parsing.cfscript.script.CFForInStatement.Decompile(CFForInStatement.java:35)
ERROR:  at cfml.parsing.cfscript.script.CFCompoundStatement.Decompile(CFCompoundStatement.java:54)
ERROR:  at cfml.parsing.cfscript.script.CFIfStatement.Decompile(CFIfStatement.java:35)
ERROR:  at cfml.parsing.cfscript.script.CFCompoundStatement.Decompile(CFCompoundStatement.java:54)
ERROR:  at cfml.parsing.cfscript.script.CFIfStatement.Decompile(CFIfStatement.java:35)
ERROR:  at cfml.parsing.cfscript.script.CFCompoundStatement.Decompile(CFCompoundStatement.java:54)
ERROR:  at cfml.parsing.cfscript.script.CFForInStatement.Decompile(CFForInStatement.java:35)
ERROR:  at cfml.parsing.cfscript.script.CFCompoundStatement.Decompile(CFCompoundStatement.java:54)
ERROR:  at cfml.parsing.cfscript.script.CFCompoundStatement.Decompile(CFCompoundStatement.java:54)
ERROR:  at cfml.parsing.cfscript.script.CFCompoundStatement.Decompile(CFCompoundStatement.java:54)
ERROR:  at cfml.parsing.cfscript.script.CFCompoundStatement.Decompile(CFCompoundStatement.java:54)
ERROR:  at cfml.parsing.cfscript.script.CFCompoundStatement.Decompile(CFCompoundStatement.java:54)
```

**Comment by ryaneberly** [comment]
Interesting.  I don't know what causes the additional logging.  I will take a look at that, but you can merge the PR if you like.  Thanks for contributing.

**Comment by tstec** [comment]
Thank you. I'll merge my change shortly.

**Comment by ryaneberly** [comment]
Thanks.

**Pull request merged**
