### PR TITLE
Rule to check for writeDump in cfset tags and script blocks

### PR DESCRIPTION
**Pull request by justinmclean**

### CODE REVIEW

**Comment by justinmclean** [comment]
100% code coverage in unit tests

**Comment by ryaneberly** [comment]
I think the expression inside cfset gets parsed.  As a CFScriptExpression?.  Not sure.  If not it probably should be.

**Comment by justinmclean** [comment]
Sadly it doesn't get parsed as a CFScriptExpression. If you comment out that method the test testWriteDumpInTag fails.

**Comment by ryaneberly** [comment]
@justinmclean 
take a look at 2337b8f

I had to dig a little big to remember how this all worked.  Not processing <cfset> sounded like a missing feature, but it is there.

You are correct that
public void expression(final CFScriptStatement expression, final Context context, final BugList bugs) 
does not get called for <cfset>

but

public void expression(final CFExpression expression, final Context context,
			final BugList bugs) 

gets called for all expressions regardless of whether its from <cfset>, <cfscript> or even nested inside another expression!

So.  the rule becomes quite simple.  No substringing required.

**Comment by justinmclean** [comment]
Great I'll fix - may need to fix a few other rules as well, but that's what's the tests are for :-)

**Comment by ryaneberly** [comment]
right :-).

**Pull request merged**
