### PR TITLE
Fix for findbug xml output

### PR DESCRIPTION
**Pull request by bferdinandus**
There where some problems with the findbugs xml. I was unable to have jenkins parse the xml file because the signature on the Method node was not valid.
Also the timestamp on the FindbugsSummary node was in the wrong format.

### CODE REVIEW

**Comment by bferdinandus** [comment]
I have tried parsing the FindBugs file with the Findbugs plugin (old style, depricated) for Jenkins, the Warnings NG plugin (followup for the Findbugs plugin) for Jenkins, and the Findbugs plugin for Intellij IDEA. All three give the same errors. 

I’ll first address the timestamp issue I found when parsing the Findbugs xml. 

`[FindBugs] [ERROR] Parsing of file 'C:\Program Files (x86)\Jenkins\workspace\CFLint test\CfLintfindbugsStyle.xml' failed due to an exception: [FindBugs] [ERROR] java.text.ParseException: Unparseable date: "1548751036" [FindBugs] [ERROR] at java.text.DateFormat.parse(Unknown Source) [FindBugs] [ERROR] at edu.umd.cs.findbugs.ProjectStats.setTimestamp(ProjectStats.java:158) [FindBugs] [ERROR] at edu.umd.cs.findbugs.SAXBugCollectionHandler.startElement(SAXBugCollectionHandler.java:323) 
`
The “unparsable date” is the timestamp on the FindBugsSummary tag in the xml file. I have looked up the xsd file in the Findbugs repository on github, and noticed that hat specific attribute should be a string. [bugcollection.xsd Line 375](https://github.com/findbugsproject/findbugs/blob/451c28097c22ef8e6f8943e5ebe6a16ff41beff7/findbugs/etc/bugcollection.xsd#L375)

In the java file [ProjectStats.java Line 162](https://github.com/findbugsproject/findbugs/blob/451c28097c22ef8e6f8943e5ebe6a16ff41beff7/findbugs/src/java/edu/umd/cs/findbugs/ProjectStats.java#L162) you can see the timestamp is parsed with the java function ‘SimpleDateFormat’ with this string as the date format  
`private static final String TIMESTAMP_FORMAT = "EEE, d MMM yyyy HH:mm:ss Z"; `

That’s why I added the format date function so the XSL transformation can print the right date format at that one specific location. 

Next problem I found was the signature attribute on the method node. According to the xsd [bugcollection.xsd Line 127](https://github.com/findbugsproject/findbugs/blob/451c28097c22ef8e6f8943e5ebe6a16ff41beff7/findbugs/etc/bugcollection.xsd#L127) the signature attribute is a required string. So, it cannot be empty. If it is empty the followin error occurs on parsing the Findbugs xml: 

`java.lang.StringIndexOutOfBoundsException: String index out of range: 0 
at java.lang.String.charAt(Unknown Source) 
at edu.umd.cs.findbugs.ba.SignatureConverter.getFirst(SignatureConverter.java:59) 
at edu.umd.cs.findbugs.MethodAnnotation.getNameInClass(MethodAnnotation.java:408) 
`

After searching throug the findbugs library and analyzing the file [SignatureConverter.java](https://github.com/findbugsproject/findbugs/blob/master/findbugs/src/java/edu/umd/cs/findbugs/ba/SignatureConverter.java) It looks like the signature must at least contain parenthesis () and a letter after that determining the return type of the function.  So `()V` is the most basic. V stands for ‘void’

**Comment by bferdinandus** [comment]
@TheRealAgentK any news about the progress on this pullrequest?

**Comment by bferdinandus** [comment]
Any news on the progress of this pullrequest?

**Comment by ryaneberly** [comment]
@bferdinandus .  Thanks for your detailed analysis, and contribution!  I apologize for moving slowly on this one.

I agree with all of your modifications -- even the timestamp one.  Findbugs seems to choose odd formats for timestamps, and is not consistent even within its own xml format!   I confirmed the latest version of spot bugs does use the format you propose on the FindBugsSummary tag.

**Pull request merged**
