### PR TITLE
Added functionality to handle include tag and statement

### PR DESCRIPTION
**Pull request by isaac-mercieca**
Added functionality to cater of files included by performing a lint process on the file when encountering an include tag or statement.

### CODE REVIEW

**Comment by isaac-mercieca** [comment]
This change is causing some issues in TestCFIncludeChecker, as the include file is not being found, maybe we can add a test file or there may also be another way to handle this issue.

**Comment by ryaneberly** [comment]
Glancing at the code, it looks great.

However, I've seen cfincludes resolved by mappings, not necessarily by
folders relative to the root.  We should have a provision to configure this.

Perhaps to mitigate this initially and deal with the testing problem,
parameterize whether includes are resolved or not?

--expand-includes yes
or
--expand-includes no

I think we either default to disabled, or quietly fail by default when the
file is not found to ease the transition for the community..  Just my 2
cents.

**Comment by isaac-mercieca** [comment]
By mappings, you are referring to the ColdFusion Administrator Mappings, as there is also the case where the template is a variable, however in this case there will be issues as during the lint process the variable value is not known.

**Comment by ryaneberly** [comment]
@isaac-mercieca, good points.  I will look at merging this in the next few weeks.  Thanks for the PR!

**Comment by ryaneberly** [comment]
@isaac-mercieca ,  good work!  your PR is merged into the dev branch.   I changed it slightly, it will quietly attempt to process the includes by default.   

If you use the commandline parameter -strictinclude, it will do the behavior you implemented.  A lint error when the included file cannot be resolved.

**Comment by isaac-mercieca** [comment]
@ryaneberly Thanks a lot for the update. I will try to enhance it to handle the ColdFusion Administrator Mappings in the near future, as well.

**Pull request closed without merging**
