### PR TITLE
Provide some rules around naming of variables and methods

### PR DESCRIPTION
**Pull request by justinmclean**
Works but still a little more to do. Need to parametrize the rules a little so users can tune them. Any suggestions?

### CODE REVIEW

**Comment by ryaneberly** [comment]
See the "MinLength" parm I added to the checker and to the test.

**Comment by justinmclean** [comment]
Refactor a bit and added new rules for method names. Mind double checking the change I made to CFlint.java to fix passing the method / function name about.

**Comment by ryaneberly** [comment]
CFLint changes look fine.  That is to get the function name into the context for the CFFunctionDeclaration itself?

**Comment by justinmclean** [comment]
Exactly it needs the function name when parsing the CFFunctionDeclaration.

**Comment by ryaneberly** [comment]
perfect. thanks

**Comment by justinmclean** [comment]
IMO this is good to go now, if no objections I'll merge into dev.

**Comment by ryaneberly** [comment]
looks good.  thanks

**Pull request merged**
