### PR TITLE
Added more tags and attributes to check in VarScoper

### PR DESCRIPTION
**Pull request by KamasamaK**

### CODE REVIEW

**Comment by ryaneberly** [comment]
Code looks good.  Got a couple failing tests to reconcile:
https://travis-ci.org/cflint/CFLint/builds/318843106?utm_source=github_status&utm_medium=notification

**Comment by KamasamaK** [comment]
Instead of having those values in `com.cflint.plugins.core.VarScoper`, do you think it would be better to utilize `com.cflint.tools.CFMLTagInfo`? From what I can tell, `isAssignmentAttribute()` should return `true` for any attribute that should be checked for local scoping.

**Comment by ryaneberly** [comment]
@KamasamaK ,  Yes that is what CFMLTagInfo.isAssignmentAttribute is for.  Though it isn't currently in use and would take some testing.

The three failing tests:

TestCFBugs_VarScoper_Names.java
remove:  new String[] { "CFStoredProc" }, 

TestCFBugs_VarScoper_TagAttr.java
remove : retval.add(new String[] { "CFMail", "Query" });

cfloop_index_413.cfc
Accept new result:  column 33 is more correct than 2,  should really be 37

**Comment by KamasamaK** [comment]
I had changed the first 2 locally already as it looked easy enough. I was trying to figure out how that integration test was even finding `idx` when I came across `CFMLTagInfo.isAssignmentAttribute` but wasn't really sure how it was working. 

Regarding the column, yes it does look like the column is more correct now, so however it found it before must not be reporting that correctly. If we take column to be number of characters, then 33 is correct. It would only be 37 if the tab counted as 4 columns. Although the other one in that file for `xxx` seems to be wrong.

Anyway, the tests are fixed now.

**Comment by ryaneberly** [comment]
Thanks @KamasamaK

**Pull request merged**
