### PR TITLE
Rule to check for unused local variables

### PR DESCRIPTION
**Pull request by justinmclean**

### CODE REVIEW

**Comment by ryaneberly** [comment]
Nice use of the new start/end functions.  

GlobalVarChecker also has a similar list of variable names to ignore.  Your's is more complete.  We could pull that out to a common utility function or even the config at some point.

**Comment by justinmclean** [comment]
The GlobalVarChecker is doing it in a nice way as well I'll refactor it.

**Comment by justinmclean** [comment]
I think this is better - any thought? All tests pass.

**Comment by ryaneberly** [comment]
Looks great.  thanks!

**Pull request merged**
